### ISSUE TITLE
hi～

### ISSUE THREAD

**Issue by Tvlog** [maguag/DELL-5488-OC-Hackintosh#1]
我来支持你了，后续更新定制可以一起弄

**Comment by Tvlog** [comment]
开机跑代码，nvram没有-v，切换图像化引导后仍会跑代码，这是基于debug做的吗？
如何关闭开机前的跑代码呢？
现升级最新open core 0.9.6正式版观察是否解决

**Comment by Tvlog** [comment]
升级最新正式版，设置图形化启动不再跑代码，成功，添加inter网卡支持，稍后提交pr

**Comment by Tvlog** [comment]
CPU friend配置不正确的电源管理数据，导致睡眠唤醒可能出现sleep wake failure in efi

**Comment by maguag** [comment]
> 开机跑代码，nvram没有-v，切换图像化引导后仍会跑代码，这是基于debug做的吗？ 如何关闭开机前的跑代码呢？ 现升级最新open core 0.9.6正式版观察是否解决

取消-v之后要reset nvram才会取消跑代码

**Comment by maguag** [comment]
> CPU friend配置不正确的电源管理数据，导致睡眠唤醒可能出现sleep wake failure in efi
应该是版本不对应吧，你是用[OCAuxiliaryTools](https://github.com/ic005k/OCAuxiliaryTools)升级的kexts吗？需要用小兵的代码重新生成一下CPUFriendDataProvider.kext

**Comment by Tvlog** [comment]
是的，我查到原因了，simbios版本对应不上，修改后唤醒现在已经没有复发了，感谢你项目的基础上修改，现在只剩下一个问题耳麦不可用了

**Comment by maguag** [comment]
我自己定制过applealc，我当时的机器正常，提交的版本把耳机麦克风节点屏蔽了，你可以试试自己定制applealc

**Comment by Tvlog** [comment]
好的，我尝试一下，谢谢你❤️

**Comment by Tvlog** [comment]
您是否还保留未屏蔽麦克风耳机节点的efi，方便发给我吗？Rayink@outlook.com
我和你同一款型号，应该可以通用使用。我在定制过程有些困难不知如何解决

**Comment by maguag** [comment]
> 您是否还保留未屏蔽麦克风耳机节点的efi，方便发给我吗？[Rayink@outlook.com](mailto:Rayink@outlook.com) 我和你同一款型号，应该可以通用使用。我在定制过程有些困难不知如何解决

没有保存了，之前的电脑出售了

**Comment by Tvlog** [comment]
> 解决

好的，也谢谢你的解答与提供的思路了，可以把这个issue关闭了
